const formCars = document.querySelector('[data-js="formCars"]')
const listCars = document.querySelector('[data-js="list-cars"]')
const inputImage = document.querySelector('[data-js="url"]')

formCars.addEventListener('submit', (event) => {
  event.preventDefault()
  const urlImage = document.createElement('td')
  urlImage.innerHTML =  String(event.target.elements.url.value)
  const modelCar = document.createElement('td')
  modelCar.innerHTML =  String(event.target.elements.model.value)
  const yearCar = document.createElement('td')
  yearCar.innerHTML =  String(event.target.elements.year.value)
  const plateCar = document.createElement('td')
  plateCar.innerHTML =  String(event.target.elements['plate-car'].value)
  const colorCar = document.createElement('td')
  colorCar.innerHTML =  String(event.target.elements['color-car'].value)

  const newCarLine = document.createElement('tr')
  newCarLine.setAttribute("data-js", "new-car")
  listCars.appendChild(newCarLine)
  const newCar = document.querySelector('[data-js="new-car"]:last-child')
  newCar.appendChild(urlImage)
  newCar.appendChild(modelCar)
  newCar.appendChild(yearCar)
  newCar.appendChild(plateCar)
  newCar.appendChild(colorCar)

  formCars.reset()
  inputImage.focus()
}, false)
